@startuml

interface IState
{
    Update() : void
}
abstract class State

class KillPlayerState
class KillBaseState

class Bot
{
    State : IState
    
    Update() : void
}

IState <|.. State

State <|-- KillPlayerState
State <|-- KillBaseState

Bot *-- IState

@enduml